routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\SellerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

require __DIR__.'/auth.php';

//******==================Start of Admin Controller***********/
Route::prefix('admin')->group(function(){
    Route::get('/login', [AdminController::class, 'Index'])->name('login_form');
    Route::post('/login/owner', [AdminController::class, 'Login'])->name('admin_login');
    Route::get('/dashboard', [AdminController::class, 'Dashboard'])->name('admin_dashboard')->middleware('admin');
    Route::get('/logout', [AdminController::class, 'adminLogout'])->name('admin_logout');

    Route::get('/register', [AdminController::class, 'adminRegister'])->name('admin_register');
    Route::post('/register/store', [AdminController::class, 'adminStore'])->name('admin_register_store');
});
//******==================End of Admin Controller***********/

//******==================Start of Seller Controller***********/
Route::prefix('seller')->group(function(){
    Route::get('/login', [SellerController::class, 'Index'])->name('seller_login_form');
    Route::post('/login/owner', [SellerController::class, 'Login'])->name('seller_login');
    Route::get('/dashboard', [SellerController::class, 'Dashboard'])->name('seller_dashboard')->middleware('seller');
    Route::get('/logout', [SellerController::class, 'sellerLogout'])->name('seller_logout');

    Route::get('/register', [SellerController::class, 'sellerRegister'])->name('seller_register');
    Route::post('/register/store', [SellerController::class, 'sellerStore'])->name('seller_register_store');
});
//******==================End of Seller Controller***********/

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/admin/index.blade.php
@extends('admin.master')
@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">

        @if (Session::has('error'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong> {{ session::get('error')}}</strong>
          </div>
        @endif
        
            <h1 class="title">Hey, I'm Admin Dashboard!</h1>
            Admin login name: {{ Auth::guard('admin')->user()->name }} <br>
            Admin Email Id: {{ Auth::guard('admin')->user()->email }} <br>

            <a href="{{ route('admin_logout') }}" class="dashboard-nav-item"><i class="fas fa-sign-out-alt"></i> Logout </a>

        </div>
    </div>
</div>

@endsection

resources/views/admin/login.blade.php
@extends('admin.master')
@section('content')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<x-guest-layout>
    <x-auth-card>
        <x-slot name="logo">
            <a href="/">
               <h3>Admin Login</h3>
            </a>
        </x-slot>

        <!-- Session Status -->
        <x-auth-session-status class="mb-4" :status="session('status')" />

        <!-- Validation Errors -->
        <x-auth-validation-errors class="mb-4" :errors="$errors" />


        @if (Session::has('success'))
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong> {{ session::get('success')}}</strong>
          </div>
        @endif

        <form method="POST" action="{{ route('admin_login') }}">
            @csrf

            <!-- Email Address -->
            <div>
                <x-label for="email" :value="__('Email')" />

                <x-input id="email" class="block mt-1 w-full" type="email" name="email" :value="old('email')" required autofocus />
            </div>

            <!-- Password -->
            <div class="mt-4">
                <x-label for="password" :value="__('Password')" />

                <x-input id="password" class="block mt-1 w-full" type="password" name="password" required autocomplete="current-password" />
            </div>

            <!-- Remember Me -->
            <div class="block mt-4">
                <label for="remember_me" class="inline-flex items-center">
                    <input id="remember_me" type="checkbox" class="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50" name="remember">
                    <span class="ml-2 text-sm text-gray-600">{{ __('Remember me') }}</span>
                    &nbsp;&nbsp;&nbsp;
                    <span>
                        <a href="{{ route('admin_register') }}">
                            <span><i class="fa fa-registered" aria-hidden="true"></i></span>
                            <span class="ml-2 text-sm text-gray-600">{{ __('New Register') }}</span>
                        </a>
                    </span>
                </label>
            </div>


            <div class="flex items-center justify-end mt-4">
                @if (Route::has('password.request'))
                    <a class="underline text-sm text-gray-600 hover:text-gray-900" href="{{ route('password.request') }}">
                        {{ __('Forgot your password?') }}
                    </a>
                @endif

                <x-button class="ml-3">
                    {{ __('Log in') }}
                </x-button>
            </div>
        </form>
    </x-auth-card>
</x-guest-layout>

    
@endsection

resources/views/admin/master.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Admin Dashboard!</title>
  </head>
  <body>



    @yield('content')




    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  </body>
</html>